// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: tools/protos/blacklist.proto

package blacklist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupportedQueryField int32

const (
	SupportedQueryField_record_id  SupportedQueryField = 0
	SupportedQueryField_client_id  SupportedQueryField = 1
	SupportedQueryField_product_id SupportedQueryField = 2
	SupportedQueryField_added_date SupportedQueryField = 4
)

// Enum value maps for SupportedQueryField.
var (
	SupportedQueryField_name = map[int32]string{
		0: "record_id",
		1: "client_id",
		2: "product_id",
		4: "added_date",
	}
	SupportedQueryField_value = map[string]int32{
		"record_id":  0,
		"client_id":  1,
		"product_id": 2,
		"added_date": 4,
	}
)

func (x SupportedQueryField) Enum() *SupportedQueryField {
	p := new(SupportedQueryField)
	*p = x
	return p
}

func (x SupportedQueryField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SupportedQueryField) Descriptor() protoreflect.EnumDescriptor {
	return file_tools_protos_blacklist_proto_enumTypes[0].Descriptor()
}

func (SupportedQueryField) Type() protoreflect.EnumType {
	return &file_tools_protos_blacklist_proto_enumTypes[0]
}

func (x SupportedQueryField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SupportedQueryField.Descriptor instead.
func (SupportedQueryField) EnumDescriptor() ([]byte, []int) {
	return file_tools_protos_blacklist_proto_rawDescGZIP(), []int{0}
}

type SupportedQueryOperation int32

const (
	SupportedQueryOperation_EQUALS       SupportedQueryOperation = 0
	SupportedQueryOperation_GREATER_THAN SupportedQueryOperation = 1
	SupportedQueryOperation_LESSER_THAN  SupportedQueryOperation = 2
	SupportedQueryOperation_BEGINS_WITH  SupportedQueryOperation = 3
)

// Enum value maps for SupportedQueryOperation.
var (
	SupportedQueryOperation_name = map[int32]string{
		0: "EQUALS",
		1: "GREATER_THAN",
		2: "LESSER_THAN",
		3: "BEGINS_WITH",
	}
	SupportedQueryOperation_value = map[string]int32{
		"EQUALS":       0,
		"GREATER_THAN": 1,
		"LESSER_THAN":  2,
		"BEGINS_WITH":  3,
	}
)

func (x SupportedQueryOperation) Enum() *SupportedQueryOperation {
	p := new(SupportedQueryOperation)
	*p = x
	return p
}

func (x SupportedQueryOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SupportedQueryOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_tools_protos_blacklist_proto_enumTypes[1].Descriptor()
}

func (SupportedQueryOperation) Type() protoreflect.EnumType {
	return &file_tools_protos_blacklist_proto_enumTypes[1]
}

func (x SupportedQueryOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SupportedQueryOperation.Descriptor instead.
func (SupportedQueryOperation) EnumDescriptor() ([]byte, []int) {
	return file_tools_protos_blacklist_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_protos_blacklist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_tools_protos_blacklist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_tools_protos_blacklist_proto_rawDescGZIP(), []int{0}
}

type BlacklistRecordDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordId  string `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	ClientId  string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ProductId string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	AddedDate string `protobuf:"bytes,4,opt,name=added_date,json=addedDate,proto3" json:"added_date,omitempty"`
}

func (x *BlacklistRecordDto) Reset() {
	*x = BlacklistRecordDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_protos_blacklist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlacklistRecordDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistRecordDto) ProtoMessage() {}

func (x *BlacklistRecordDto) ProtoReflect() protoreflect.Message {
	mi := &file_tools_protos_blacklist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistRecordDto.ProtoReflect.Descriptor instead.
func (*BlacklistRecordDto) Descriptor() ([]byte, []int) {
	return file_tools_protos_blacklist_proto_rawDescGZIP(), []int{1}
}

func (x *BlacklistRecordDto) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *BlacklistRecordDto) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BlacklistRecordDto) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *BlacklistRecordDto) GetAddedDate() string {
	if x != nil {
		return x.AddedDate
	}
	return ""
}

type BlacklistRecordOperationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordId  string `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	ClientId  string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ProductId string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (x *BlacklistRecordOperationRequest) Reset() {
	*x = BlacklistRecordOperationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_protos_blacklist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlacklistRecordOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistRecordOperationRequest) ProtoMessage() {}

func (x *BlacklistRecordOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tools_protos_blacklist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistRecordOperationRequest.ProtoReflect.Descriptor instead.
func (*BlacklistRecordOperationRequest) Descriptor() ([]byte, []int) {
	return file_tools_protos_blacklist_proto_rawDescGZIP(), []int{2}
}

func (x *BlacklistRecordOperationRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *BlacklistRecordOperationRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *BlacklistRecordOperationRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type BlacklistBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*BlacklistRecordOperationRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *BlacklistBatchRequest) Reset() {
	*x = BlacklistBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_protos_blacklist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlacklistBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistBatchRequest) ProtoMessage() {}

func (x *BlacklistBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tools_protos_blacklist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistBatchRequest.ProtoReflect.Descriptor instead.
func (*BlacklistBatchRequest) Descriptor() ([]byte, []int) {
	return file_tools_protos_blacklist_proto_rawDescGZIP(), []int{3}
}

func (x *BlacklistBatchRequest) GetRequests() []*BlacklistRecordOperationRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type BlacklistRecordQueriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queries        []*BlacklistRecordQueryRequest   `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	BetweenQueries []*BlacklistRecordBetweenRequest `protobuf:"bytes,2,rep,name=betweenQueries,proto3" json:"betweenQueries,omitempty"`
}

func (x *BlacklistRecordQueriesRequest) Reset() {
	*x = BlacklistRecordQueriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_protos_blacklist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlacklistRecordQueriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistRecordQueriesRequest) ProtoMessage() {}

func (x *BlacklistRecordQueriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tools_protos_blacklist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistRecordQueriesRequest.ProtoReflect.Descriptor instead.
func (*BlacklistRecordQueriesRequest) Descriptor() ([]byte, []int) {
	return file_tools_protos_blacklist_proto_rawDescGZIP(), []int{4}
}

func (x *BlacklistRecordQueriesRequest) GetQueries() []*BlacklistRecordQueryRequest {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *BlacklistRecordQueriesRequest) GetBetweenQueries() []*BlacklistRecordBetweenRequest {
	if x != nil {
		return x.BetweenQueries
	}
	return nil
}

type BlacklistRecordBetweenQueriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queries []*BlacklistRecordBetweenRequest `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
}

func (x *BlacklistRecordBetweenQueriesRequest) Reset() {
	*x = BlacklistRecordBetweenQueriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_protos_blacklist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlacklistRecordBetweenQueriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistRecordBetweenQueriesRequest) ProtoMessage() {}

func (x *BlacklistRecordBetweenQueriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tools_protos_blacklist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistRecordBetweenQueriesRequest.ProtoReflect.Descriptor instead.
func (*BlacklistRecordBetweenQueriesRequest) Descriptor() ([]byte, []int) {
	return file_tools_protos_blacklist_proto_rawDescGZIP(), []int{5}
}

func (x *BlacklistRecordBetweenQueriesRequest) GetQueries() []*BlacklistRecordBetweenRequest {
	if x != nil {
		return x.Queries
	}
	return nil
}

type BlacklistRecordQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field     SupportedQueryField     `protobuf:"varint,1,opt,name=field,proto3,enum=SupportedQueryField" json:"field,omitempty"`
	Operation SupportedQueryOperation `protobuf:"varint,2,opt,name=operation,proto3,enum=SupportedQueryOperation" json:"operation,omitempty"`
	Value     string                  `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BlacklistRecordQueryRequest) Reset() {
	*x = BlacklistRecordQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_protos_blacklist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlacklistRecordQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistRecordQueryRequest) ProtoMessage() {}

func (x *BlacklistRecordQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tools_protos_blacklist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistRecordQueryRequest.ProtoReflect.Descriptor instead.
func (*BlacklistRecordQueryRequest) Descriptor() ([]byte, []int) {
	return file_tools_protos_blacklist_proto_rawDescGZIP(), []int{6}
}

func (x *BlacklistRecordQueryRequest) GetField() SupportedQueryField {
	if x != nil {
		return x.Field
	}
	return SupportedQueryField_record_id
}

func (x *BlacklistRecordQueryRequest) GetOperation() SupportedQueryOperation {
	if x != nil {
		return x.Operation
	}
	return SupportedQueryOperation_EQUALS
}

func (x *BlacklistRecordQueryRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type BlacklistRecordBetweenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field SupportedQueryField `protobuf:"varint,1,opt,name=field,proto3,enum=SupportedQueryField" json:"field,omitempty"`
	Init  string              `protobuf:"bytes,2,opt,name=init,proto3" json:"init,omitempty"`
	End   string              `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *BlacklistRecordBetweenRequest) Reset() {
	*x = BlacklistRecordBetweenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tools_protos_blacklist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlacklistRecordBetweenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistRecordBetweenRequest) ProtoMessage() {}

func (x *BlacklistRecordBetweenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tools_protos_blacklist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistRecordBetweenRequest.ProtoReflect.Descriptor instead.
func (*BlacklistRecordBetweenRequest) Descriptor() ([]byte, []int) {
	return file_tools_protos_blacklist_proto_rawDescGZIP(), []int{7}
}

func (x *BlacklistRecordBetweenRequest) GetField() SupportedQueryField {
	if x != nil {
		return x.Field
	}
	return SupportedQueryField_record_id
}

func (x *BlacklistRecordBetweenRequest) GetInit() string {
	if x != nil {
		return x.Init
	}
	return ""
}

func (x *BlacklistRecordBetweenRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

var File_tools_protos_blacklist_proto protoreflect.FileDescriptor

var file_tools_protos_blacklist_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62,
	0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x8c, 0x01, 0x0a, 0x12, 0x42, 0x6c, 0x61, 0x63,
	0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x74, 0x6f, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x65, 0x64,
	0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x64,
	0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x7a, 0x0a, 0x1f, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x49, 0x64, 0x22, 0x55, 0x0a, 0x15, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x08, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x9f, 0x01, 0x0a, 0x1d, 0x42, 0x6c,
	0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x51, 0x75, 0x65,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x07, 0x71,
	0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x46, 0x0a, 0x0e, 0x62, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x51, 0x75,
	0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x42, 0x6c,
	0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65, 0x74,
	0x77, 0x65, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0e, 0x62, 0x65, 0x74,
	0x77, 0x65, 0x65, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x60, 0x0a, 0x24, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65,
	0x74, 0x77, 0x65, 0x65, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65, 0x74, 0x77, 0x65, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x97, 0x01,
	0x0a, 0x1b, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a,
	0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x36, 0x0a, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x71, 0x0a, 0x1d, 0x42, 0x6c, 0x61, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65, 0x74, 0x77, 0x65, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x05, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x2a, 0x53, 0x0a, 0x13, 0x53, 0x75,
	0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x0d, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x10, 0x01, 0x12,
	0x0e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x10, 0x02, 0x12,
	0x0e, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x10, 0x04, 0x2a,
	0x59, 0x0a, 0x17, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x51,
	0x55, 0x41, 0x4c, 0x53, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x52, 0x45, 0x41, 0x54, 0x45,
	0x52, 0x5f, 0x54, 0x48, 0x41, 0x4e, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x45, 0x53, 0x53,
	0x45, 0x52, 0x5f, 0x54, 0x48, 0x41, 0x4e, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x45, 0x47,
	0x49, 0x4e, 0x53, 0x5f, 0x57, 0x49, 0x54, 0x48, 0x10, 0x03, 0x32, 0x95, 0x04, 0x0a, 0x09, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x4b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x20,
	0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x44, 0x74, 0x6f, 0x12, 0x4a, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x61, 0x63,
	0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x16, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x74, 0x6f, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x51, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1e, 0x2e,
	0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x51,
	0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44,
	0x74, 0x6f, 0x30, 0x01, 0x12, 0x4c, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65, 0x42, 0x6c, 0x61, 0x63,
	0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x2e, 0x42, 0x6c,
	0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44,
	0x74, 0x6f, 0x12, 0x4b, 0x0a, 0x18, 0x53, 0x61, 0x76, 0x65, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x16,
	0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x74, 0x6f, 0x28, 0x01, 0x30, 0x01, 0x12,
	0x41, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x3e, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x12, 0x16, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x28, 0x01, 0x42, 0x13, 0x5a, 0x11, 0x7a, 0x6f, 0x72, 0x72, 0x65, 0x72, 0x6f, 0x2f, 0x62, 0x6c,
	0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tools_protos_blacklist_proto_rawDescOnce sync.Once
	file_tools_protos_blacklist_proto_rawDescData = file_tools_protos_blacklist_proto_rawDesc
)

func file_tools_protos_blacklist_proto_rawDescGZIP() []byte {
	file_tools_protos_blacklist_proto_rawDescOnce.Do(func() {
		file_tools_protos_blacklist_proto_rawDescData = protoimpl.X.CompressGZIP(file_tools_protos_blacklist_proto_rawDescData)
	})
	return file_tools_protos_blacklist_proto_rawDescData
}

var file_tools_protos_blacklist_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tools_protos_blacklist_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tools_protos_blacklist_proto_goTypes = []interface{}{
	(SupportedQueryField)(0),                     // 0: SupportedQueryField
	(SupportedQueryOperation)(0),                 // 1: SupportedQueryOperation
	(*Empty)(nil),                                // 2: Empty
	(*BlacklistRecordDto)(nil),                   // 3: BlacklistRecordDto
	(*BlacklistRecordOperationRequest)(nil),      // 4: BlacklistRecordOperationRequest
	(*BlacklistBatchRequest)(nil),                // 5: BlacklistBatchRequest
	(*BlacklistRecordQueriesRequest)(nil),        // 6: BlacklistRecordQueriesRequest
	(*BlacklistRecordBetweenQueriesRequest)(nil), // 7: BlacklistRecordBetweenQueriesRequest
	(*BlacklistRecordQueryRequest)(nil),          // 8: BlacklistRecordQueryRequest
	(*BlacklistRecordBetweenRequest)(nil),        // 9: BlacklistRecordBetweenRequest
}
var file_tools_protos_blacklist_proto_depIdxs = []int32{
	4,  // 0: BlacklistBatchRequest.requests:type_name -> BlacklistRecordOperationRequest
	8,  // 1: BlacklistRecordQueriesRequest.queries:type_name -> BlacklistRecordQueryRequest
	9,  // 2: BlacklistRecordQueriesRequest.betweenQueries:type_name -> BlacklistRecordBetweenRequest
	9,  // 3: BlacklistRecordBetweenQueriesRequest.queries:type_name -> BlacklistRecordBetweenRequest
	0,  // 4: BlacklistRecordQueryRequest.field:type_name -> SupportedQueryField
	1,  // 5: BlacklistRecordQueryRequest.operation:type_name -> SupportedQueryOperation
	0,  // 6: BlacklistRecordBetweenRequest.field:type_name -> SupportedQueryField
	4,  // 7: Blacklist.GetBlacklistRecord:input_type -> BlacklistRecordOperationRequest
	5,  // 8: Blacklist.GetBlacklistRecordBatch:input_type -> BlacklistBatchRequest
	6,  // 9: Blacklist.GetBlacklistRecordsQuery:input_type -> BlacklistRecordQueriesRequest
	4,  // 10: Blacklist.SaveBlacklistRecord:input_type -> BlacklistRecordOperationRequest
	5,  // 11: Blacklist.SaveBlacklistRecordBatch:input_type -> BlacklistBatchRequest
	4,  // 12: Blacklist.DeleteBlacklistRecord:input_type -> BlacklistRecordOperationRequest
	5,  // 13: Blacklist.DeleteBatchBlacklistRecord:input_type -> BlacklistBatchRequest
	3,  // 14: Blacklist.GetBlacklistRecord:output_type -> BlacklistRecordDto
	3,  // 15: Blacklist.GetBlacklistRecordBatch:output_type -> BlacklistRecordDto
	3,  // 16: Blacklist.GetBlacklistRecordsQuery:output_type -> BlacklistRecordDto
	3,  // 17: Blacklist.SaveBlacklistRecord:output_type -> BlacklistRecordDto
	3,  // 18: Blacklist.SaveBlacklistRecordBatch:output_type -> BlacklistRecordDto
	2,  // 19: Blacklist.DeleteBlacklistRecord:output_type -> Empty
	2,  // 20: Blacklist.DeleteBatchBlacklistRecord:output_type -> Empty
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_tools_protos_blacklist_proto_init() }
func file_tools_protos_blacklist_proto_init() {
	if File_tools_protos_blacklist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tools_protos_blacklist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tools_protos_blacklist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlacklistRecordDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tools_protos_blacklist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlacklistRecordOperationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tools_protos_blacklist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlacklistBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tools_protos_blacklist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlacklistRecordQueriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tools_protos_blacklist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlacklistRecordBetweenQueriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tools_protos_blacklist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlacklistRecordQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tools_protos_blacklist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlacklistRecordBetweenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tools_protos_blacklist_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tools_protos_blacklist_proto_goTypes,
		DependencyIndexes: file_tools_protos_blacklist_proto_depIdxs,
		EnumInfos:         file_tools_protos_blacklist_proto_enumTypes,
		MessageInfos:      file_tools_protos_blacklist_proto_msgTypes,
	}.Build()
	File_tools_protos_blacklist_proto = out.File
	file_tools_protos_blacklist_proto_rawDesc = nil
	file_tools_protos_blacklist_proto_goTypes = nil
	file_tools_protos_blacklist_proto_depIdxs = nil
}
