// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: protos/blacklist.proto

package blacklist

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlacklistClient is the client API for Blacklist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlacklistClient interface {
	GetBlacklistRecordById(ctx context.Context, in *BlacklistRequest, opts ...grpc.CallOption) (*BlacklistRecordDto, error)
	GetBlacklistRecordBatch(ctx context.Context, opts ...grpc.CallOption) (Blacklist_GetBlacklistRecordBatchClient, error)
	SaveBlacklistRecord(ctx context.Context, in *BlacklistRecordDto, opts ...grpc.CallOption) (*BlacklistRecordDto, error)
	SaveBlacklistRecordBatch(ctx context.Context, opts ...grpc.CallOption) (Blacklist_SaveBlacklistRecordBatchClient, error)
}

type blacklistClient struct {
	cc grpc.ClientConnInterface
}

func NewBlacklistClient(cc grpc.ClientConnInterface) BlacklistClient {
	return &blacklistClient{cc}
}

func (c *blacklistClient) GetBlacklistRecordById(ctx context.Context, in *BlacklistRequest, opts ...grpc.CallOption) (*BlacklistRecordDto, error) {
	out := new(BlacklistRecordDto)
	err := c.cc.Invoke(ctx, "/Blacklist/GetBlacklistRecordById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blacklistClient) GetBlacklistRecordBatch(ctx context.Context, opts ...grpc.CallOption) (Blacklist_GetBlacklistRecordBatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &Blacklist_ServiceDesc.Streams[0], "/Blacklist/GetBlacklistRecordBatch", opts...)
	if err != nil {
		return nil, err
	}
	x := &blacklistGetBlacklistRecordBatchClient{stream}
	return x, nil
}

type Blacklist_GetBlacklistRecordBatchClient interface {
	Send(*BlacklistRequest) error
	Recv() (*BlacklistRecordDto, error)
	grpc.ClientStream
}

type blacklistGetBlacklistRecordBatchClient struct {
	grpc.ClientStream
}

func (x *blacklistGetBlacklistRecordBatchClient) Send(m *BlacklistRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *blacklistGetBlacklistRecordBatchClient) Recv() (*BlacklistRecordDto, error) {
	m := new(BlacklistRecordDto)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *blacklistClient) SaveBlacklistRecord(ctx context.Context, in *BlacklistRecordDto, opts ...grpc.CallOption) (*BlacklistRecordDto, error) {
	out := new(BlacklistRecordDto)
	err := c.cc.Invoke(ctx, "/Blacklist/SaveBlacklistRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blacklistClient) SaveBlacklistRecordBatch(ctx context.Context, opts ...grpc.CallOption) (Blacklist_SaveBlacklistRecordBatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &Blacklist_ServiceDesc.Streams[1], "/Blacklist/SaveBlacklistRecordBatch", opts...)
	if err != nil {
		return nil, err
	}
	x := &blacklistSaveBlacklistRecordBatchClient{stream}
	return x, nil
}

type Blacklist_SaveBlacklistRecordBatchClient interface {
	Send(*BlacklistRecordDto) error
	Recv() (*BlacklistRecordDto, error)
	grpc.ClientStream
}

type blacklistSaveBlacklistRecordBatchClient struct {
	grpc.ClientStream
}

func (x *blacklistSaveBlacklistRecordBatchClient) Send(m *BlacklistRecordDto) error {
	return x.ClientStream.SendMsg(m)
}

func (x *blacklistSaveBlacklistRecordBatchClient) Recv() (*BlacklistRecordDto, error) {
	m := new(BlacklistRecordDto)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlacklistServer is the server API for Blacklist service.
// All implementations must embed UnimplementedBlacklistServer
// for forward compatibility
type BlacklistServer interface {
	GetBlacklistRecordById(context.Context, *BlacklistRequest) (*BlacklistRecordDto, error)
	GetBlacklistRecordBatch(Blacklist_GetBlacklistRecordBatchServer) error
	SaveBlacklistRecord(context.Context, *BlacklistRecordDto) (*BlacklistRecordDto, error)
	SaveBlacklistRecordBatch(Blacklist_SaveBlacklistRecordBatchServer) error
	mustEmbedUnimplementedBlacklistServer()
}

// UnimplementedBlacklistServer must be embedded to have forward compatible implementations.
type UnimplementedBlacklistServer struct {
}

func (UnimplementedBlacklistServer) GetBlacklistRecordById(context.Context, *BlacklistRequest) (*BlacklistRecordDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlacklistRecordById not implemented")
}
func (UnimplementedBlacklistServer) GetBlacklistRecordBatch(Blacklist_GetBlacklistRecordBatchServer) error {
	return status.Errorf(codes.Unimplemented, "method GetBlacklistRecordBatch not implemented")
}
func (UnimplementedBlacklistServer) SaveBlacklistRecord(context.Context, *BlacklistRecordDto) (*BlacklistRecordDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveBlacklistRecord not implemented")
}
func (UnimplementedBlacklistServer) SaveBlacklistRecordBatch(Blacklist_SaveBlacklistRecordBatchServer) error {
	return status.Errorf(codes.Unimplemented, "method SaveBlacklistRecordBatch not implemented")
}
func (UnimplementedBlacklistServer) mustEmbedUnimplementedBlacklistServer() {}

// UnsafeBlacklistServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlacklistServer will
// result in compilation errors.
type UnsafeBlacklistServer interface {
	mustEmbedUnimplementedBlacklistServer()
}

func RegisterBlacklistServer(s grpc.ServiceRegistrar, srv BlacklistServer) {
	s.RegisterService(&Blacklist_ServiceDesc, srv)
}

func _Blacklist_GetBlacklistRecordById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlacklistServer).GetBlacklistRecordById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Blacklist/GetBlacklistRecordById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlacklistServer).GetBlacklistRecordById(ctx, req.(*BlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blacklist_GetBlacklistRecordBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BlacklistServer).GetBlacklistRecordBatch(&blacklistGetBlacklistRecordBatchServer{stream})
}

type Blacklist_GetBlacklistRecordBatchServer interface {
	Send(*BlacklistRecordDto) error
	Recv() (*BlacklistRequest, error)
	grpc.ServerStream
}

type blacklistGetBlacklistRecordBatchServer struct {
	grpc.ServerStream
}

func (x *blacklistGetBlacklistRecordBatchServer) Send(m *BlacklistRecordDto) error {
	return x.ServerStream.SendMsg(m)
}

func (x *blacklistGetBlacklistRecordBatchServer) Recv() (*BlacklistRequest, error) {
	m := new(BlacklistRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Blacklist_SaveBlacklistRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlacklistRecordDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlacklistServer).SaveBlacklistRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Blacklist/SaveBlacklistRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlacklistServer).SaveBlacklistRecord(ctx, req.(*BlacklistRecordDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _Blacklist_SaveBlacklistRecordBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BlacklistServer).SaveBlacklistRecordBatch(&blacklistSaveBlacklistRecordBatchServer{stream})
}

type Blacklist_SaveBlacklistRecordBatchServer interface {
	Send(*BlacklistRecordDto) error
	Recv() (*BlacklistRecordDto, error)
	grpc.ServerStream
}

type blacklistSaveBlacklistRecordBatchServer struct {
	grpc.ServerStream
}

func (x *blacklistSaveBlacklistRecordBatchServer) Send(m *BlacklistRecordDto) error {
	return x.ServerStream.SendMsg(m)
}

func (x *blacklistSaveBlacklistRecordBatchServer) Recv() (*BlacklistRecordDto, error) {
	m := new(BlacklistRecordDto)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Blacklist_ServiceDesc is the grpc.ServiceDesc for Blacklist service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Blacklist_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Blacklist",
	HandlerType: (*BlacklistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlacklistRecordById",
			Handler:    _Blacklist_GetBlacklistRecordById_Handler,
		},
		{
			MethodName: "SaveBlacklistRecord",
			Handler:    _Blacklist_SaveBlacklistRecord_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBlacklistRecordBatch",
			Handler:       _Blacklist_GetBlacklistRecordBatch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SaveBlacklistRecordBatch",
			Handler:       _Blacklist_SaveBlacklistRecordBatch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/blacklist.proto",
}
