// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: protos/blacklist.proto

package blacklist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlacklistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BlacklistRequest) Reset() {
	*x = BlacklistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_blacklist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistRequest) ProtoMessage() {}

func (x *BlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blacklist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistRequest.ProtoReflect.Descriptor instead.
func (*BlacklistRequest) Descriptor() ([]byte, []int) {
	return file_protos_blacklist_proto_rawDescGZIP(), []int{0}
}

func (x *BlacklistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BlacklistBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
}

func (x *BlacklistBatchRequest) Reset() {
	*x = BlacklistBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_blacklist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlacklistBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistBatchRequest) ProtoMessage() {}

func (x *BlacklistBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blacklist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistBatchRequest.ProtoReflect.Descriptor instead.
func (*BlacklistBatchRequest) Descriptor() ([]byte, []int) {
	return file_protos_blacklist_proto_rawDescGZIP(), []int{1}
}

func (x *BlacklistBatchRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type BlacklistRecordDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Restrictions []*RestrictionDto `protobuf:"bytes,2,rep,name=restrictions,proto3" json:"restrictions,omitempty"`
}

func (x *BlacklistRecordDto) Reset() {
	*x = BlacklistRecordDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_blacklist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlacklistRecordDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistRecordDto) ProtoMessage() {}

func (x *BlacklistRecordDto) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blacklist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistRecordDto.ProtoReflect.Descriptor instead.
func (*BlacklistRecordDto) Descriptor() ([]byte, []int) {
	return file_protos_blacklist_proto_rawDescGZIP(), []int{2}
}

func (x *BlacklistRecordDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlacklistRecordDto) GetRestrictions() []*RestrictionDto {
	if x != nil {
		return x.Restrictions
	}
	return nil
}

type RestrictionDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId  string      `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Product   *ProductDto `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	AddedDate string      `protobuf:"bytes,3,opt,name=added_date,json=addedDate,proto3" json:"added_date,omitempty"`
}

func (x *RestrictionDto) Reset() {
	*x = RestrictionDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_blacklist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestrictionDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestrictionDto) ProtoMessage() {}

func (x *RestrictionDto) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blacklist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestrictionDto.ProtoReflect.Descriptor instead.
func (*RestrictionDto) Descriptor() ([]byte, []int) {
	return file_protos_blacklist_proto_rawDescGZIP(), []int{3}
}

func (x *RestrictionDto) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RestrictionDto) GetProduct() *ProductDto {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *RestrictionDto) GetAddedDate() string {
	if x != nil {
		return x.AddedDate
	}
	return ""
}

type ProductDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductName string `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductId   string `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (x *ProductDto) Reset() {
	*x = ProductDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_blacklist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDto) ProtoMessage() {}

func (x *ProductDto) ProtoReflect() protoreflect.Message {
	mi := &file_protos_blacklist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDto.ProtoReflect.Descriptor instead.
func (*ProductDto) Descriptor() ([]byte, []int) {
	return file_protos_blacklist_proto_rawDescGZIP(), []int{4}
}

func (x *ProductDto) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductDto) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

var File_protos_blacklist_proto protoreflect.FileDescriptor

var file_protos_blacklist_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x10, 0x42, 0x6c, 0x61, 0x63,
	0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x15,
	0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x12, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x33, 0x0a, 0x0c, 0x72,
	0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x74, 0x6f, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x73, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x74, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x25, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x74, 0x6f, 0x52, 0x07, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x65, 0x64, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x64, 0x65,
	0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x4e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x44, 0x74, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x64, 0x32, 0x9f, 0x02, 0x0a, 0x09, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x79, 0x49, 0x64, 0x12, 0x11, 0x2e,
	0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x44, 0x74, 0x6f, 0x12, 0x45, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x61, 0x63,
	0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x12, 0x11, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x74, 0x6f, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3f, 0x0a, 0x13,
	0x53, 0x61, 0x76, 0x65, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x13, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x74, 0x6f, 0x1a, 0x13, 0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x74, 0x6f, 0x12, 0x48, 0x0a,
	0x18, 0x53, 0x61, 0x76, 0x65, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x13, 0x2e, 0x42, 0x6c, 0x61, 0x63,
	0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x74, 0x6f, 0x1a, 0x13,
	0x2e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x44, 0x74, 0x6f, 0x28, 0x01, 0x30, 0x01, 0x42, 0x13, 0x5a, 0x11, 0x7a, 0x6f, 0x72, 0x72, 0x65,
	0x72, 0x6f, 0x2f, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_blacklist_proto_rawDescOnce sync.Once
	file_protos_blacklist_proto_rawDescData = file_protos_blacklist_proto_rawDesc
)

func file_protos_blacklist_proto_rawDescGZIP() []byte {
	file_protos_blacklist_proto_rawDescOnce.Do(func() {
		file_protos_blacklist_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_blacklist_proto_rawDescData)
	})
	return file_protos_blacklist_proto_rawDescData
}

var file_protos_blacklist_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_blacklist_proto_goTypes = []interface{}{
	(*BlacklistRequest)(nil),      // 0: BlacklistRequest
	(*BlacklistBatchRequest)(nil), // 1: BlacklistBatchRequest
	(*BlacklistRecordDto)(nil),    // 2: BlacklistRecordDto
	(*RestrictionDto)(nil),        // 3: RestrictionDto
	(*ProductDto)(nil),            // 4: ProductDto
}
var file_protos_blacklist_proto_depIdxs = []int32{
	3, // 0: BlacklistRecordDto.restrictions:type_name -> RestrictionDto
	4, // 1: RestrictionDto.product:type_name -> ProductDto
	0, // 2: Blacklist.GetBlacklistRecordById:input_type -> BlacklistRequest
	0, // 3: Blacklist.GetBlacklistRecordBatch:input_type -> BlacklistRequest
	2, // 4: Blacklist.SaveBlacklistRecord:input_type -> BlacklistRecordDto
	2, // 5: Blacklist.SaveBlacklistRecordBatch:input_type -> BlacklistRecordDto
	2, // 6: Blacklist.GetBlacklistRecordById:output_type -> BlacklistRecordDto
	2, // 7: Blacklist.GetBlacklistRecordBatch:output_type -> BlacklistRecordDto
	2, // 8: Blacklist.SaveBlacklistRecord:output_type -> BlacklistRecordDto
	2, // 9: Blacklist.SaveBlacklistRecordBatch:output_type -> BlacklistRecordDto
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_blacklist_proto_init() }
func file_protos_blacklist_proto_init() {
	if File_protos_blacklist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_blacklist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlacklistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_blacklist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlacklistBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_blacklist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlacklistRecordDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_blacklist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestrictionDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_blacklist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_blacklist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_blacklist_proto_goTypes,
		DependencyIndexes: file_protos_blacklist_proto_depIdxs,
		MessageInfos:      file_protos_blacklist_proto_msgTypes,
	}.Build()
	File_protos_blacklist_proto = out.File
	file_protos_blacklist_proto_rawDesc = nil
	file_protos_blacklist_proto_goTypes = nil
	file_protos_blacklist_proto_depIdxs = nil
}
